[package]
name = "project_manufacturers"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }